<?php
/**
 * Created by PhpStorm.
 * User: g361183
 * Date: 4/13/20
 * Time: 5:57 PM
 */

namespace App\Repository;

use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping;
use MongoDB\Driver\Query;

class ActHiVarinstRepository extends EntityRepository
{
    public function __construct(EntityManagerInterface $em, Mapping\ClassMetadata $class)
    {
        parent::__construct($em, $class);
    }


    public function findAll()
    {
        return parent::findAll(); // TODO: Change the autogenerated stub
    }
    public function findWorkflowStatus($start=0,$offset=100)
    {
        $qb=$this->createQueryBuilder('ahvs');
        $qb->select('ahvs')
            ->setMaxResults($offset)
            ->setFirstResult($start);
        return $qb->getQuery()->getArrayResult();
    }

}