<?php
/**
 * Created by PhpStorm.
 * User: g361183
 * Date: 4/13/20
 * Time: 5:59 PM
 */

namespace App\Repository;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping;

class VariablesRepository extends EntityRepository
{

    public function __construct(EntityManagerInterface $em, Mapping\ClassMetadata $class)
    {
        parent::__construct($em, $class);
    }

    public function findAll()
    {
        return parent::findAll(); // TODO: Change the autogenerated stub
    }
    public function getAllVariables($start=0,$offset=100)
    {
        $qb=$this->createQueryBuilder('variables');
        $qb->select('variables.processName')
            ->andWhere('variables.processName like :processName')
            ->andWhere('variables.langue =:langue')
            ->setParameter('processName',"%GEDDSM%")
            ->setParameter('langue',"fr")
            ->setMaxResults($offset)
            ->setFirstResult($start);
        return $qb->getQuery()->getArrayResult();
    }
}