parameters:
    cas_logout_url: 'https://secure-kb.comon/cas/logout'
    ldap_url: 'intranet.comon/webservices/metaopen/employees_search.php'
    path_export_csv: '/var/data/reporting/export_csv/'

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    PRayno\CasAuthBundle\Event\LogoutSuccessHandler:
        arguments:
          $logoutUrl: "%cas_logout_url%"

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Service\LdapService:
        arguments: ['%ldap_url%']
    App\Service\ExportCsvFileService:
            arguments: ['%path_export_csv%']

    App\Repository\:
        resource: '../src/Repository'